---
- name: "Carregar SSH Config"
  include_tasks: ssh_config.yml
  tags: [ssh_hardening, security]

- name: "Incluindo politicas de senha"
  include_tasks: password_policy.yml
  tags: [policy_hardening, security]