---
- name: "Carregar SSH Config"
  include_tasks:
    file: ssh_config.yml
  apply:
    tags: [ssh_hardening, security]
  tags: [ssh_hardening, security]

- name: "Incluindo politicas de senha"
  include_tasks:
    file: password_policy.yml
  apply:
    tags: [policy_hardening, security]
  tags: [policy_hardening, security]
