---
- name: Configurar expiração de senha para 90 dias
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MAX_DAYS'
    line: 'PASS_MAX_DAYS   90'
  tags: [policy_hardening, security]
