---
- name: Configurar expiração de senha para 90 dias
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MAX_DAYS'
    line: 'PASS_MAX_DAYS   90'
  tags: [policy_hardening, security, pass_max_days]

- name: "Configurar expiração mínima da senha (7 dias)"
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MIN_DAYS'
    line: 'PASS_MIN_DAYS   7'
  tags: [password_policy, security, pass_min_days]

- name: "Configurar aviso de expiração (14 dias antes)"
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_WARN_AGE'
    line: 'PASS_WARN_AGE   14'
  tags: [password_policy, security, warning_expiration]