---
- name: Desabilitar login de root via SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  tags: [ssh_hardening, security]

- name: Task de teste de visibilidade
  ansible.builtin.debug:
    msg: "Eu existo e fui alcançada!"
  tags: [testar]