---
# ===== Identidade da instância =====
oracle_version: "19.3.0"

# ===== Estrutura de diretórios Oracle =====
oracle_base_root: "{{ BASE_DIR }}"
oracle_base: "{{ BASE_DIR }}/{{ INST }}"
oracle_home: "{{ oracle_base }}/{{ oracle_version }}"
oracle_inventory: "{{ oracle_base }}/oraInventory"
oracle_rsp_file: "{{ oracle_home }}/install/response/db_install.rsp"

# ===== Artefatos de instalação =====
oracle_preinstall_rpm_file: "oracle-database-preinstall-19c-1.0-2.el9.x86_64.rpm"
oracle_preinstall_rpm_url: "http://192.168.137.138:8080/{{ oracle_preinstall_rpm_file }}"
oracle_preinstall_rpm_dest: "/tmp/{{ oracle_preinstall_rpm_file }}"

oracle_db_zip_file: "LINUX.X64_193000_db_home.zip"
oracle_db_zip_url: "http://192.168.137.138:8080/{{ oracle_db_zip_file }}"
oracle_db_zip_dest: "/tmp/{{ oracle_db_zip_file }}"

# ===== Compatibilidade Oracle 19c em RHEL 9 =====
oracle_cv_assume_distid: "RHEL8"

oracle_required_packages:
  - libnsl
  - libaio
  - libaio-devel
  - unzip
  - tar
  - ksh
  - binutils
  - gcc
  - make
  - glibc
  - glibc-devel
  - util-linux
  - smartmontools

# ===== Storage / LVM =====
# Ajuste conforme seu ambiente
VG_NAME: "vg_oracle"
oracle_disk_device: "/dev/sdb"

oracle_lvs:
  - lv_name: "lv_oracle"
    size: "100%FREE"
    mount_path: "{{ BASE_DIR }}"