---
# Variáveis de Identidade (Vêm do Survey)
INST: "{{ oracle_inst_name | upper }}"
VG_NAME: "vg_{{ oracle_inst_name | lower }}"
BASE_DIR: "/oracle"  # <-- Remova a instância daqui

# Lista técnica com caminhos corrigidos (BASE_DIR=/oracle | INST=PATOD)
oracle_lvs:
  - { lv_name: "lv_{{ INST | lower }}", mount_path: "{{ BASE_DIR }}/{{ INST }}",           size: "{{ lv_tstor_size }}G" }
  - { lv_name: "lv_oradata",           mount_path: "{{ BASE_DIR }}/{{ INST }}/oradata",   size: "{{ lv_oradata_size }}G" }
  - { lv_name: "lv_mirrlogA",          mount_path: "{{ BASE_DIR }}/{{ INST }}/mirrlogA",  size: "{{ lv_mirrlogA_size }}G" }
  - { lv_name: "lv_mirrlogB",          mount_path: "{{ BASE_DIR }}/{{ INST }}/mirrlogB",  size: "{{ lv_mirrlogB_size }}G" }
  - { lv_name: "lv_ologA",             mount_path: "{{ BASE_DIR }}/{{ INST }}/ologA",     size: "{{ lv_ologA_size }}G" }
  - { lv_name: "lv_ologB",             mount_path: "{{ BASE_DIR }}/{{ INST }}/ologB",     size: "{{ lv_ologB_size }}G" }
  - { lv_name: "lv_arch",              mount_path: "{{ BASE_DIR }}/{{ INST }}/arch",      size: "{{ lv_arch_size }}G" }
  - { lv_name: "lv_undo",              mount_path: "{{ BASE_DIR }}/{{ INST }}/undo",      size: "{{ lv_undo_size }}G" }
  - { lv_name: "lv_temp",              mount_path: "{{ BASE_DIR }}/{{ INST }}/temp",      size: "{{ lv_temp_size }}G" }