SET VERIFY OFF
connect "SYS"/"&&sysPassword" as SYSDBA
set echo on
spool /oracle/TSTOR/scripts/db_creation/TSTOR/CreateDBFiles.log append
CREATE SMALLFILE TABLESPACE "USERS" LOGGING DATAFILE '/oracle/TSTOR/oradata1/users01.dbf' SIZE 200M REUSE EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
ALTER DATABASE DEFAULT TABLESPACE "USERS";
CREATE TABLESPACE TS_AUDIT_DAT01 DATAFILE '/oracle/TSTOR/oradata1/TS_AUDIT_DAT01_01.DBF' size 1000M 
REUSE EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_PERFSTAT_DAT01 DATAFILE '/oracle/TSTOR/oradata1/TS_PERFSTAT_DAT01.DBF' size 1000M REUSE EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_TSTOR_DAT01 DATAFILE '/oracle/TSTOR/oradata1/TS_TSTOR_DAT01_01.DBF' size 1000M REUSE EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_TSTOR_IDX01 DATAFILE '/oracle/TSTOR/oradata1/TS_TSTOR_IDX_01.DBF' size 1000M REUSE EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
spool off

select 'CREATE TABLESPACE ' || tablespace_name || ' DATAFILE ''/oracle/TSTOR/oradata1/' || substr( file_name,instr(file_name,'\',-1)+1 || '''' || 'size ' || from dba_data_files where tablespace_name not like 'IDX%' ORDER BY TABLESPACE_NAME, FILE_ID;


