---
- name: "Instalar Repositorio PGDG (PostgreSQL Global Development Group)"
  ansible.builtin.dnf:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present
    disable_gpg_check: yes
  tags: [postgres, install]

- name: "Desabilitar modulo padrao de postgres do AppStream"
  ansible.builtin.command:
    cmd: dnf -qy module disable postgresql
  changed_when: false
  tags: [postgres, install]

- name: "Instalar Pacotes do PostgreSQL 16"
  ansible.builtin.dnf:
    name:
      - postgresql16-server
      - postgresql16-contrib
    state: present
  tags: [postgres, install]

- name: "Inicializar o Banco de Dados (initdb)"
  ansible.builtin.command:
    cmd: /usr/pgsql-16/bin/postgresql-16-setup initdb
    creates: /var/lib/pgsql/16/data/PG_VERSION
  tags: [postgres, setup]

- name: "Habilitar e Iniciar o servico"
  ansible.builtin.service:
    name: postgresql-16
    state: started
    enabled: yes
  tags: [postgres, service]