---
- name: restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: restart chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted

- name: restart ufw
  ansible.builtin.systemd:
    name: ufw
    state: restarted
