---
- name: "Baixar Binário do Oracle 19.3 via HTTP"
  ansible.builtin.get_url:
    url: "http://192.168.137.138:8080/LINUX.X64_193000_db_home.zip" # Valide este IP!
    dest: "/tmp/oracle_sig.zip"
    mode: '0644'
    timeout: 1200
  tags: [install, download]

- name: "Garantir que o diretório ORACLE_HOME existe"
  ansible.builtin.file:
    path: "{{ BASE_DIR }}/19.3.0"
    state: directory
    owner: oracle
    group: oinstall
    mode: '0755'
  tags: [install, directory]

- name: "Descompactar Binários no ORACLE_HOME"
  ansible.builtin.unarchive:
    src: "/tmp/oracle_sig.zip"
    dest: "{{ BASE_DIR }}/19.3.0"
    remote_src: yes
    owner: oracle
    group: oinstall
  tags: [install]

- name: "Gerar Arquivo de Resposta a partir do Template"
  ansible.builtin.template:
    src: db_install.rsp.j2
    dest: "/tmp/db_install.rsp"
    owner: oracle
    group: oinstall
    mode: '0644'
  tags: [install]

- name: "Executar Instalação Silenciosa do Software Oracle"
  ansible.builtin.shell:
    cmd: "./runInstaller -silent -waitforcompletion -responseFile /tmp/db_install.rsp -ignorePrereq"
    chdir: "{{ BASE_DIR }}/19.3.0"
  become: yes
  become_user: oracle
  environment:
    CV_ASSUME_DISTID: "OEL8.4" 
  register: oracle_install_result
  failed_when: "'Successfully Setup Software' not in oracle_install_result.stdout"
  tags: [install]

# --- SCRIPTS DE ROOT (A ordem importa!) ---

- name: "Executar scripts de Root (orainstRoot.sh)"
  ansible.builtin.shell: "/oracle/oraInventory/orainstRoot.sh"
  become: yes
  tags: [install]

- name: "Executar scripts de Root (root.sh)"
  ansible.builtin.shell: "{{ BASE_DIR }}/19.3.0/root.sh"
  become: yes
  tags: [install]