---
- name: "Executar Instalação Silenciosa do Oracle (Correção ELF 64-bit)"
  ansible.builtin.shell:
    cmd: >
      export CV_ASSUME_DISTID=RHEL8;
      export ORACLE_HOME={{ BASE_DIR }}/{{ INST }}/19.3.0;
      export LD_LIBRARY_PATH=$ORACLE_HOME/lib:/usr/lib64:/lib64;
      ./runInstaller -silent 
      -responseFile {{ BASE_DIR }}/{{ INST }}/19.3.0/install/response/db_install.rsp 
      -ignorePrereq 
      -waitforcompletion 
      oracle.install.option=INSTALL_DB_SWONLY 
      ORACLE_HOSTNAME={{ ansible_hostname }} 
      UNIX_GROUP_NAME=oinstall 
      INVENTORY_LOCATION={{ BASE_DIR }}/oraInventory 
      SELECTED_LANGUAGES=en 
      ORACLE_HOME={{ BASE_DIR }}/{{ INST }}/19.3.0 
      ORACLE_BASE={{ BASE_DIR }}/{{ INST }} 
      oracle.install.db.InstallEdition=EE 
      oracle.install.db.OSDBA_GROUP=dba 
      oracle.install.db.OSBACKUPDBA_GROUP=dba 
      oracle.install.db.OSDGDBA_GROUP=dba 
      oracle.install.db.OSKMDBA_GROUP=kmdba 
      oracle.install.db.OSRACDBA_GROUP=dba 
      SECURITY_UPDATES_VIA_MYORACLESUPPORT=false 
      DECLINE_SECURITY_UPDATES=true
    chdir: "{{ BASE_DIR }}/{{ INST }}/19.3.0"
  become: yes
  become_user: oracle
  environment:
    CV_ASSUME_DISTID: "RHEL8"
    ORACLE_HOME: "{{ BASE_DIR }}/{{ INST }}/19.3.0"
    ORACLE_BASE: "{{ BASE_DIR }}/{{ INST }}"
    LD_LIBRARY_PATH: "{{ BASE_DIR }}/{{ INST }}/19.3.0/lib:/usr/lib64:/lib64"
  tags: [install, silent_installation]

- name: "Executar orainstRoot.sh (Dinâmico)"
  ansible.builtin.shell: "{{ BASE_DIR }}/{{ INST }}/oraInventory/orainstRoot.sh"
  become: yes
  become_user: root
  tags: [install, root_scripts]

- name: "Executar root.sh (Dinâmico)"
  ansible.builtin.shell: "{{ BASE_DIR }}/{{ INST }}/19.3.0/root.sh"
  become: yes
  become_user: root
  tags: [install, root_scripts]