---
- name: "Instalar bibliotecas de compatibilidade críticas para RHEL 9"
  ansible.builtin.dnf:
    name:
      - libnsl
      - libnsl.i686
      - libxcrypt-compat
      - glibc-devel
    state: present
  become: yes
  tags: [install, libs]

- name: "Limpar inventário para nova tentativa"
  ansible.builtin.shell: "rm -rf /oracle/oraInventory/*"
  become: yes
  tags: [install, clean_inventory]

- name: "Limpar ORACLE_HOME sujo de falhas anteriores"
  ansible.builtin.shell: "rm -rf {{ BASE_DIR }}/19.3.0/*"
  become: yes
  tags: [install, clean_home]

- name: "Descompactar Binários no ORACLE_HOME"
  ansible.builtin.unarchive:
    src: "/tmp/oracle_sig.zip" # O arquivo ZIP já deve estar no /tmp
    dest: "{{ BASE_DIR }}/19.3.0"
    remote_src: yes
    owner: oracle
    group: oinstall
  tags: [install, unzip_binary]

- name: "Gerar Arquivo de Resposta a partir do Template"
  ansible.builtin.template:
    src: db_install.rsp.j2
    dest: "/tmp/db_install.rsp"
    owner: oracle
    group: oinstall
  tags: [install, rsp_file]

- name: "Executar Instalação Silenciosa do Software Oracle"
  ansible.builtin.shell:
    cmd: "./runInstaller -silent -waitforcompletion -ignorePrereqFailure -responseFile /tmp/db_install.rsp"
    chdir: "{{ BASE_DIR }}/19.3.0"
  become: yes
  become_user: oracle
  environment:
    CV_ASSUME_DISTID: "OEL8.4" 
  register: oracle_install_result
  failed_when: "'Successfully Setup Software' not in oracle_install_result.stdout"
  tags: [install, silent_installation]

- name: "Executar scripts de Root (orainstRoot.sh)"
  ansible.builtin.shell: "/oracle/oraInventory/orainstRoot.sh"
  become: yes
  tags: [install, instroot]

- name: "Executar scripts de Root (root.sh)"
  ansible.builtin.shell: "{{ BASE_DIR }}/19.3.0/root.sh"
  become: yes
  tags: [install, rootsh]