---
- name: "Preparar storage LVM para Oracle"
  ansible.builtin.include_tasks: storage_lvm.yml
  tags:
    - storage

- name: "Executar pré-instalação do Oracle"
  ansible.builtin.include_tasks: pre_install.yml
  tags:
    - pre_install

- name: "Executar instalação do Oracle"
  ansible.builtin.include_tasks: install_db.yml
  tags:
    - install
    - silent_installation
    - root_scripts