---
- name: "Configurar Storage e LVM"
  ansible.builtin.include_tasks: storage_lvm.yml
  # A tag 'always' garante que o Ansible entre no arquivo independente das tags do Job
  tags: [always, storage, lvm]

- name: "Pre-requisitos e Usuários"
  ansible.builtin.include_tasks: pre_install.yml
  tags: [always, pre_install]

- name: "Instalação do Banco"
  ansible.builtin.include_tasks: install_db.yml
  tags: [always, install]