---
- name: "Baixar RPM do Preinstall via HTTP"
  ansible.builtin.get_url:
    url: "http://192.168.137.138:8080/oracle-database-preinstall-19c-1.0-1.el9.x86_64.rpm"
    dest: "/tmp/oracle-database-preinstall-19c.rpm"
    mode: '0644'

- name: "Instalar Oracle Preinstall (Cria usuário oracle)"
  ansible.builtin.dnf:
    name: "/tmp/oracle-database-preinstall-19c.rpm"
    state: present
    disable_gpg_check: yes
  tags: [pre_install, packages]

- name: "Ajustar Dono e Grupo da estrutura de diretórios"
  ansible.builtin.file:
    path: "{{ BASE_DIR }}"
    state: directory
    owner: oracle
    group: oinstall
    recurse: yes
  tags: [pre_install, permissions]