---
- name: "Transferir RPM do Preinstall do Servidor AWX para o Destino"
  ansible.builtin.get_url:
    url: "http://192.168.137.138:8080/oracle-database-preinstall-19c-1.0-2.el9.x86_64.rpm"
    dest: "/tmp/oracle-database-preinstall-19c-1.0-2.el9.x86_64.rpm"
    mode: '0644'
  tags: [pre_install, copy]

- name: "Instalar Oracle Preinstall (Cria usuário oracle e grupos)"
  ansible.builtin.dnf:
    name: "/tmp/oracle-database-preinstall-19c-1.0-2.el9.x86_64.rpm"
    state: present
    disable_gpg_check: yes
  tags: [pre_install, packages]

- name: "Criar diretório do Home apenas se não existir (Alta Performance)"
  ansible.builtin.shell: "mkdir -p {{ BASE_DIR }}/{{ INST }}/19.3.0/install/response"
  args:
    creates: "{{ BASE_DIR }}/{{ INST }}/19.3.0/install/response"
  become: yes
  tags: [install, setup_dirs]

- name: "Baixar binário do Oracle Database via HTTP"
  ansible.builtin.get_url:
    url: "http://192.168.137.138:8080/LINUX.X64_193000_db_home.zip"
    dest: "/tmp/LINUX.X64_193000_db_home.zip"
    mode: '0644'
    timeout: 900
  tags: [install, download_bin]

- name: "Descompactar binário via Shell"
  ansible.builtin.shell: "unzip -qo /tmp/LINUX.X64_193000_db_home.zip -d {{ BASE_DIR }}/{{ INST }}/19.3.0/"
  become: yes
  become_user: oracle 
  args:
    creates: "{{ BASE_DIR }}/{{ INST }}/19.3.0/runInstaller"

- name: "Garantir dono e permissão na raiz da instância (Rápido)"
  ansible.builtin.file:
    path: "{{ BASE_DIR }}/{{ INST }}"
    state: directory
    owner: oracle
    group: oinstall
    mode: '0775'
    recurse: no 
  become: yes
  tags: [install, setup_dirs]

- name: "Limpar rastro de inventário antigo (Pointer file /etc/oraInst.loc)"
  ansible.builtin.file:
    path: "/etc/oraInst.loc"
    state: absent
  tags: [pre_install, cleanup]

- name: "Garantir que o diretório oraInventory existe com permissões corretas"
  ansible.builtin.file:
    path: "{{ BASE_DIR }}/oraInventory"
    state: directory
    owner: oracle
    group: oinstall
    mode: '0775'
    recurse: yes 
  become: yes
  tags: [pre_install, inventory]

- name: "Aplicar chown no BASE_DIR"
  ansible.builtin.shell: "chown -R oracle:oinstall {{ BASE_DIR }}"
  become: yes
  tags: [pre_install, storage_perms]

- name: "Configurar variáveis de ambiente (.bash_profile)"
  ansible.builtin.blockinfile:
    path: /home/oracle/.bash_profile
    marker: "# {mark} ANSIBLE MANAGED BLOCK - ORACLE ENV"
    block: |
      umask 0022
      TMOUT=1800
      ORACLE_BASE={{ BASE_DIR }};export ORACLE_BASE
      ORACLE_HOME=$ORACLE_BASE/19.3.0;export ORACLE_HOME
      ORACLE_SID={{ INST }};export ORACLE_SID
      PATH=$ORACLE_HOME/bin:$PATH;export PATH
      LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib;export LD_LIBRARY_PATH
      ORACLE_HOSTNAME=`hostname`;export ORACLE_HOSTNAME
      CV_ASSUME_DISTID=RHEL8;export CV_ASSUME_DISTID
  become: yes
  tags: [pre_install, env]

- name: "Garantir permissões na pasta tmp do Ansible para o usuário oracle"
  ansible.builtin.file:
    path: "/home/oracle/.ansible/tmp"
    state: directory
    owner: oracle
    group: oinstall
    mode: '0755'
  tags: [pre_install, ansible_tmp]

- name: "Criar arquivo de resposta base (Corrigido para 19c)"
  ansible.builtin.copy:
    dest: "{{ BASE_DIR }}/{{ INST }}/19.3.0/install/response/db_install.rsp"
    content: |
      oracle.install.responseFileVersion=/oracle/install/rspconf.6.0.0
      oracle.install.option=INSTALL_DB_SWONLY
      ORACLE_HOSTNAME={{ ansible_hostname }}
      UNIX_GROUP_NAME=oinstall
      INVENTORY_LOCATION={{ BASE_DIR }}/{{ INST }}/oraInventory
      SELECTED_LANGUAGES=en
      ORACLE_HOME={{ BASE_DIR }}/{{ INST }}/19.3.0
      ORACLE_BASE={{ BASE_DIR }}/{{ INST }}
      oracle.install.db.InstallEdition=EE
      oracle.install.db.OSDBA_GROUP=dba
      oracle.install.db.OSBACKUPDBA_GROUP=dba
      oracle.install.db.OSDGDBA_GROUP=dba
      oracle.install.db.OSKMDBA_GROUP=kmdba
      oracle.install.db.OSRACDBA_GROUP=dba
      SECURITY_UPDATES_VIA_MYORACLESUPPORT=false
      DECLINE_SECURITY_UPDATES=true
    owner: oracle
    group: oinstall
    mode: '0644'
  become: yes
  tags: [install, setup_rsp]

  - name: "Limpar inventário sujo para permitir re-instalação (Dinâmico)"
  ansible.builtin.file:
    path: "{{ BASE_DIR }}/{{ INST }}/oraInventory"
    state: absent
  become: yes
  tags: [install, cleanup_inventory]

- name: "Recriar diretório do inventário vazio"
  ansible.builtin.file:
    path: "{{ BASE_DIR }}/{{ INST }}/oraInventory"
    state: directory
    owner: oracle
    group: oinstall
    mode: '0775'
  become: yes
  tags: [install, setup_dirs]