---
- name: "Criar Volume Group para o Oracle"
  community.general.lvg:
    vg: vg_oracle
    pvs: /dev/sdb
  become: yes
  tags: [always, storage, lvm]

- name: "Criar Logical Volume para o Oracle"
  community.general.lvol:
    vg: vg_oracle
    lv: lv_oracle
    size: 50G # Ajuste conforme sua necessidade
  become: yes
  tags: [always, storage, lvm]

- name: "Criar Sistema de Arquivos XFS"
  community.general.filesystem:
    fstype: xfs
    dev: /dev/vg_oracle/lv_oracle
  become: yes
  tags: [always, storage, lvm]

- name: "Montar o diretório /oracle"
  ansible.builtin.mount:
    path: "{{ BASE_DIR }}"
    src: /dev/vg_oracle/lv_oracle
    fstype: xfs
    state: mounted
  become: yes
  tags: [always, storage, lvm]