ALTER PROFILE "APPLICATION" LIMIT
  COMPOSITE_LIMIT DEFAULT
  SESSIONS_PER_USER DEFAULT
  CPU_PER_SESSION DEFAULT
  CPU_PER_CALL DEFAULT
  LOGICAL_READS_PER_SESSION DEFAULT
  LOGICAL_READS_PER_CALL DEFAULT
  IDLE_TIME DEFAULT
  CONNECT_TIME DEFAULT
  PRIVATE_SGA DEFAULT
  FAILED_LOGIN_ATTEMPTS 3
  PASSWORD_LIFE_TIME UNLIMITED
  PASSWORD_REUSE_TIME 15552000/84600
  PASSWORD_REUSE_MAX 1
  PASSWORD_VERIFY_FUNCTION "VERIFY_FUNCTION"
  PASSWORD_LOCK_TIME DEFAULT
  PASSWORD_GRACE_TIME DEFAULT;

ALTER PROFILE "DEFAULT" LIMIT
  COMPOSITE_LIMIT UNLIMITED
  SESSIONS_PER_USER UNLIMITED
  CPU_PER_SESSION UNLIMITED
  CPU_PER_CALL UNLIMITED
  LOGICAL_READS_PER_SESSION UNLIMITED
  LOGICAL_READS_PER_CALL UNLIMITED
  IDLE_TIME UNLIMITED
  CONNECT_TIME UNLIMITED
  PRIVATE_SGA UNLIMITED
  FAILED_LOGIN_ATTEMPTS 3
  PASSWORD_LIFE_TIME 7776000/86400
  PASSWORD_REUSE_TIME 15552000/86400
  PASSWORD_REUSE_MAX 1
  PASSWORD_VERIFY_FUNCTION "VERIFY_FUNCTION"
  PASSWORD_LOCK_TIME 86400/86400
  PASSWORD_GRACE_TIME 604800/86400;