-- Generated by Ansible — oracle_security_hardening role, item 2.1
-- Functions: complexity_check, string_distance, verify_function_12C
-- Executed as: sqlplus -s / as sysdba @<this_file>
WHENEVER SQLERROR EXIT FAILURE;

CREATE OR REPLACE FUNCTION sys.complexity_check
(password varchar2,
 chars integer := NULL,
 letter integer := NULL,
 upper integer := NULL,
 lower integer := NULL,
 digit integer := NULL,
 special integer := NULL)
RETURN boolean IS
   digit_array varchar2(10) := '0123456789';
   alpha_array varchar2(26) := 'abcdefghijklmnopqrstuvwxyz';
   cnt_letter integer := 0;
   cnt_upper integer := 0;
   cnt_lower integer := 0;
   cnt_digit integer := 0;
   cnt_special integer := 0;
   delimiter boolean := FALSE;
   at_sign boolean   :=FALSE;
   len INTEGER := NVL (length(password), 0);
   i integer ;
   ch CHAR(1);
BEGIN
   IF len > 256 THEN
      raise_application_error(-20020, 'Password length more than 256');
   END IF;

   FOR i in 1..len LOOP
      ch := substr(password, i, 1);
      IF ch = '"' THEN
         delimiter := TRUE;
      ELSIF ch ='@' THEN
         at_sign := TRUE;
      ELSIF instr(digit_array, ch) > 0 THEN
         cnt_digit := cnt_digit + 1;
      ELSIF instr(alpha_array, NLS_LOWER(ch)) > 0 THEN
         cnt_letter := cnt_letter + 1;
         IF ch = NLS_LOWER(ch) THEN
            cnt_lower := cnt_lower + 1;
         ELSE
            cnt_upper := cnt_upper + 1;
         END IF;
      ELSE
         cnt_special := cnt_special + 1;
      END IF;
   END LOOP;

   IF delimiter = TRUE THEN
      raise_application_error(-20012, 'password must NOT contain a '
                               || 'double-quote character, which is '
                               || 'reserved as a password delimiter');
   END IF;
   IF at_sign = TRUE THEN
      raise_application_error(-20012, 'password must NOT contain an '
                               || '@ (at) character, which is '
                               || 'reserved as connection string delimiter');
   END IF;
   IF chars IS NOT NULL AND len < chars THEN
      raise_application_error(-20001, 'Password length less than ' ||
                              chars);
   END IF;
   IF letter IS NOT NULL AND cnt_letter < letter THEN
      raise_application_error(-20022, 'Password must contain at least ' ||
                                      letter || ' letter(s)');
   END IF;
   IF upper IS NOT NULL AND cnt_upper < upper THEN
      raise_application_error(-20023, 'Password must contain at least ' ||
                                      upper || ' uppercase character(s)');
   END IF;
   IF lower IS NOT NULL AND cnt_lower < lower THEN
      raise_application_error(-20024, 'Password must contain at least ' ||
                                      lower || ' lowercase character(s)');
   END IF;
   IF digit IS NOT NULL AND cnt_digit < digit THEN
      raise_application_error(-20025, 'Password must contain at least ' ||
                                      digit || ' digit(s)');
   END IF;
   IF special IS NOT NULL AND cnt_special < special THEN
      raise_application_error(-20026, 'Password must contain at least ' ||
                                      special || ' special character(s)');
   END IF;

   RETURN(TRUE);
END;
/

CREATE OR REPLACE FUNCTION sys.string_distance
(s varchar2,
 t varchar2)
RETURN integer IS
   s_len    INTEGER := NVL (length(s), 0);
   t_len    INTEGER := NVL (length(t), 0);
   TYPE arr_type is TABLE OF NUMBER INDEX BY BINARY_INTEGER;
   d_col    arr_type ;
   dist     INTEGER := 0;
BEGIN
   IF s_len = 0 THEN
      dist := t_len;
   ELSIF t_len = 0 THEN
      dist := s_len;
   ELSE
      FOR j IN 1 .. (t_len+1) * (s_len+1) - 1 LOOP
          d_col(j) := 0 ;
      END LOOP;
      FOR i IN 0 .. s_len LOOP
          d_col(i) := i;
      END LOOP;
      FOR j IN 1 .. t_len LOOP
          d_col(j * (s_len + 1)) := j;
      END LOOP;

      FOR i IN 1.. s_len LOOP
        FOR j IN 1 .. t_len LOOP
          IF substr(s, i, 1) = substr(t, j, 1)
          THEN
             d_col(j * (s_len + 1) + i) := d_col((j-1) * (s_len+1) + i-1) ;
          ELSE
             d_col(j * (s_len + 1) + i) := LEAST (
                       d_col( j * (s_len+1) + (i-1)) + 1,
                       d_col((j-1) * (s_len+1) + i) + 1,
                       d_col((j-1) * (s_len+1) + i-1) + 1 ) ;
          END IF ;
        END LOOP;
      END LOOP;
      dist :=  d_col(t_len * (s_len+1) + s_len);
   END IF;

   RETURN (dist);
END;
/

CREATE OR REPLACE FUNCTION sys.verify_function_12C
(username varchar2,
 password varchar2,
 old_password varchar2)
RETURN boolean IS
   differ integer;
   db_name varchar2(40);
   i integer;
   i_char varchar2(10);
   simple_password varchar2(10);
   reverse_user varchar2(32);
BEGIN
   IF NOT complexity_check(password, chars => 10, upper => 2, lower => 2,
                           digit => 2, special => 2) THEN
      RETURN(FALSE);
   END IF;

   IF NLS_LOWER(password) = NLS_LOWER(username) THEN
     raise_application_error(-20002, 'Password same as or similar to user');
   END IF;
   FOR i IN 1..100 LOOP
      i_char := to_char(i);
      if NLS_LOWER(username)|| i_char = NLS_LOWER(password) THEN
        raise_application_error(-20005, 'Password same as or similar to '
                                        || 'username ');
      END IF;
   END LOOP;

   FOR i in REVERSE 1..length(username) LOOP
     reverse_user := reverse_user || substr(username, i, 1);
   END LOOP;
   IF NLS_LOWER(password) = NLS_LOWER(reverse_user) THEN
     raise_application_error(-20003, 'Password same as username reversed');
   END IF;

   select name into db_name from sys.v$database;
   if NLS_LOWER(db_name) = NLS_LOWER(password) THEN
      raise_application_error(-20004, 'Password same as or similar '
                                      || 'to server name');
   END IF;
   FOR i IN 1..100 LOOP
      i_char := to_char(i);
      if NLS_LOWER(db_name)|| i_char = NLS_LOWER(password) THEN
        raise_application_error(-20005, 'Password same as or similar '
                                        || 'to server name ');
      END IF;
   END LOOP;

   IF NLS_LOWER(password) IN ('welcome1', 'database1', 'account1', 'user1234',
                              'password1', 'oracle123', 'computer1',
                              'abcdefg1', 'change_on_install','sansumg123') THEN
      raise_application_error(-20006, 'Password too simple');
   END IF;

   simple_password := 'oracle';
   FOR i IN 1..100 LOOP
      i_char := to_char(i);
      if simple_password || i_char = NLS_LOWER(password) THEN
        raise_application_error(-20006, 'Password too simple ');
      END IF;
   END LOOP;

   simple_password := 'samsung';
   FOR i IN 1..100 LOOP
      i_char := to_char(i);
      if simple_password || i_char = NLS_LOWER(password) THEN
        raise_application_error(-20006, 'Password too simple ');
      END IF;
   END LOOP;
   IF NLS_LOWER(password) like '%samsung%' THEN
       raise_application_error(-20006, 'Password too simple ');
   END IF;

   IF old_password IS NOT NULL THEN
     differ := string_distance(old_password, password);
     IF differ < 3 THEN
        raise_application_error(-20032, 'Password should differ from previous '
                                || 'password by at least 3 characters');
     END IF;
   END IF ;

   RETURN(TRUE);
END;
/

GRANT EXECUTE ON sys.verify_function_12C TO PUBLIC;

EXIT;
