---
fci_primary_node: "sqlvm01"
fci_secondary_node: "sqlvm02"
fci_primary_ip: "192.168.137.170"
fci_secondary_ip: "192.168.137.171"
fci_virtual_name: "SQLHA-SQL"
fci_virtual_ip: "192.168.137.173"
fci_cluster_network: "Cluster Network 1"
fci_shared_disk_letter: "S"
fci_shared_disk_label: "SQLShared"
fci_instance_name: "MSSQLSERVER"
fci_instance_dir: "S:\\SQL"
fci_data_dir: "S:\\SQL\\Data"
fci_log_dir: "S:\\SQL\\Log"
fci_backup_dir: "S:\\SQL\\Backup"
fci_temp_dir: "C:\\ansible_temp"
fci_iso_url: "http://192.168.137.148:8080/sqlserver/SQLServer2025-x64-ENU.iso"
fci_ssms_url: "http://192.168.137.148:8080/sqlserver/SSMS-Setup-ENU.exe"
