[observability_server]
obs-server ansible_host=192.168.137.200

[rhel9]
obs-agent1 ansible_host=192.168.137.201
obs-agent2 ansible_host=192.168.137.202

[linux_agents:children]
rhel9

[windows_agents]
# win-host1 ansible_host=192.168.137.x ansible_connection=winrm ansible_winrm_transport=ntlm

[all:vars]
ansible_python_interpreter=/usr/bin/python3
