---
- name: Provisionamento Automático de Bancos de Dados
  hosts: "{{ target_hosts | default('all') }}"
  become: yes

  roles:
    - role: ../roles/postgres_install
      when: db_type == "postgres"
      tags: [postgres, database]