---
- name: "Manage SQL Server users"
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: "SQL Server: manage user via survey vars"
      ansible.builtin.include_role:
        name: sql_manage_users
      tags: [sqlserver, sql_users]
