---
- name: "Manage PostgreSQL users"
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: "PostgreSQL: manage user via survey vars"
      ansible.builtin.include_role:
        name: postgres_manage_users
      tags: [postgres, postgres_users]
