---
- name: "Manage Oracle users"
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: "Oracle: manage user via survey vars"
      ansible.builtin.include_role:
        name: oracle_manage_users
      tags: [oracle, oracle_users]
